import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col h-screen w-full absolute">
          <div className="grid grid-cols-2 gap-20 bg-[#B87A00] h-3/5 pt-10 px-10 pb-10">
            <div className="bg-slate-200 text-black rounded-t-3xl">
              <div className="h-1/10">
                <Header/>
              </div>

              DESCRIPTION
            </div>
            <div className="bg-slate-500">
              CODE
            </div>
          </div>
          <div className="grid grid-cols-2 bg-[#FFCF60] h-2/5">
            RENDER
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
